version: '3.8'

services:
  medicalxai-api:
    image: medicalxai-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medicalxai-api
    environment:
      - NODE_ENV=production
      - PORT=3001
      - URL_DATABASE=mongodb+srv://21521571:07kUEfsLdpZjAklR@cluster0.hmcpcf4.mongodb.net/DocInSight
      - ACCESS_TOKEN_SECRET=csnklcndslkncaojowiejoijcsdj31421
      - REFRESH_TOKEN_SECRET=csjancjknsjancklajcoiweji829u8943rud
      - CLOUDINARY_USER_NAME=dano2vyry
      - CLOUDINARY_API_KEY=152882116935543
      - CLOUDINARY_API_SECRET=M8Bsl2PXcG4umT-zKOTO718RXuI
      - MAILTRAP_USERNAME=HRManagement2003@gmail.com
      - MAILTRAP_PASSWORD=yhej kkvh rdxt eply
    ports:
      - '3001:80'
    restart: always